// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: janction/videoRendering/v1/types.proto

package videoRendering

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type VideoRenderingLogs_VideoRenderingLog_SEVERITY int32

const (
	VideoRenderingLogs_VideoRenderingLog_INFO    VideoRenderingLogs_VideoRenderingLog_SEVERITY = 0
	VideoRenderingLogs_VideoRenderingLog_SUCCESS VideoRenderingLogs_VideoRenderingLog_SEVERITY = 1
	VideoRenderingLogs_VideoRenderingLog_ERROR   VideoRenderingLogs_VideoRenderingLog_SEVERITY = 2
)

var VideoRenderingLogs_VideoRenderingLog_SEVERITY_name = map[int32]string{
	0: "INFO",
	1: "SUCCESS",
	2: "ERROR",
}

var VideoRenderingLogs_VideoRenderingLog_SEVERITY_value = map[string]int32{
	"INFO":    0,
	"SUCCESS": 1,
	"ERROR":   2,
}

func (x VideoRenderingLogs_VideoRenderingLog_SEVERITY) String() string {
	return proto.EnumName(VideoRenderingLogs_VideoRenderingLog_SEVERITY_name, int32(x))
}

func (VideoRenderingLogs_VideoRenderingLog_SEVERITY) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{7, 0, 0}
}

// Params defines the parameters of the module.
type Params struct {
	VideoRenderingKeyName string `protobuf:"bytes,1,opt,name=video_rendering_key_name,json=videoRenderingKeyName,proto3" json:"video_rendering_key_name,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetVideoRenderingKeyName() string {
	if m != nil {
		return m.VideoRenderingKeyName
	}
	return ""
}

// GenesisState is the state that must be provided at genesis.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// Video Rendering Task index
	VideoRenderingTaskInfo VideoRenderingTaskInfo `protobuf:"bytes,3,opt,name=videoRenderingTaskInfo,proto3" json:"videoRenderingTaskInfo"`
	// List of Video Rendering tasks
	VideoRenderingTaskList []IndexedVideoRenderingTask `protobuf:"bytes,4,rep,name=videoRenderingTaskList,proto3" json:"videoRenderingTaskList"`
	// List of Workers
	Workers []Worker `protobuf:"bytes,5,rep,name=workers,proto3" json:"workers"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetVideoRenderingTaskInfo() VideoRenderingTaskInfo {
	if m != nil {
		return m.VideoRenderingTaskInfo
	}
	return VideoRenderingTaskInfo{}
}

func (m *GenesisState) GetVideoRenderingTaskList() []IndexedVideoRenderingTask {
	if m != nil {
		return m.VideoRenderingTaskList
	}
	return nil
}

func (m *GenesisState) GetWorkers() []Worker {
	if m != nil {
		return m.Workers
	}
	return nil
}

type Worker struct {
	Address            string             `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Reputation         *Worker_Reputation `protobuf:"bytes,3,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Enabled            bool               `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CurrentTaskId      string             `protobuf:"bytes,5,opt,name=current_task_id,json=currentTaskId,proto3" json:"current_task_id,omitempty"`
	CurrentThreadIndex uint32             `protobuf:"varint,6,opt,name=current_thread_index,json=currentThreadIndex,proto3" json:"current_thread_index,omitempty"`
}

func (m *Worker) Reset()         { *m = Worker{} }
func (m *Worker) String() string { return proto.CompactTextString(m) }
func (*Worker) ProtoMessage()    {}
func (*Worker) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{2}
}
func (m *Worker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Worker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Worker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Worker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker.Merge(m, src)
}
func (m *Worker) XXX_Size() int {
	return m.Size()
}
func (m *Worker) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker.DiscardUnknown(m)
}

var xxx_messageInfo_Worker proto.InternalMessageInfo

func (m *Worker) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Worker) GetReputation() *Worker_Reputation {
	if m != nil {
		return m.Reputation
	}
	return nil
}

func (m *Worker) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Worker) GetCurrentTaskId() string {
	if m != nil {
		return m.CurrentTaskId
	}
	return ""
}

func (m *Worker) GetCurrentThreadIndex() uint32 {
	if m != nil {
		return m.CurrentThreadIndex
	}
	return 0
}

type Worker_Reputation struct {
	Stacked     uint64 `protobuf:"varint,1,opt,name=stacked,proto3" json:"stacked,omitempty"`
	Points      int64  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	Validations uint32 `protobuf:"varint,3,opt,name=validations,proto3" json:"validations,omitempty"`
	Solutions   uint32 `protobuf:"varint,4,opt,name=solutions,proto3" json:"solutions,omitempty"`
}

func (m *Worker_Reputation) Reset()         { *m = Worker_Reputation{} }
func (m *Worker_Reputation) String() string { return proto.CompactTextString(m) }
func (*Worker_Reputation) ProtoMessage()    {}
func (*Worker_Reputation) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{2, 0}
}
func (m *Worker_Reputation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Worker_Reputation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Worker_Reputation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Worker_Reputation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Worker_Reputation.Merge(m, src)
}
func (m *Worker_Reputation) XXX_Size() int {
	return m.Size()
}
func (m *Worker_Reputation) XXX_DiscardUnknown() {
	xxx_messageInfo_Worker_Reputation.DiscardUnknown(m)
}

var xxx_messageInfo_Worker_Reputation proto.InternalMessageInfo

func (m *Worker_Reputation) GetStacked() uint64 {
	if m != nil {
		return m.Stacked
	}
	return 0
}

func (m *Worker_Reputation) GetPoints() int64 {
	if m != nil {
		return m.Points
	}
	return 0
}

func (m *Worker_Reputation) GetValidations() uint32 {
	if m != nil {
		return m.Validations
	}
	return 0
}

func (m *Worker_Reputation) GetSolutions() uint32 {
	if m != nil {
		return m.Solutions
	}
	return 0
}

// Video Rendering Task
// @cid the IPFS CID submitted by a task requester
type VideoRenderingTask struct {
	TaskId       string                  `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Requester    string                  `protobuf:"bytes,2,opt,name=requester,proto3" json:"requester,omitempty"`
	Cid          string                  `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	StartFrame   uint32                  `protobuf:"varint,4,opt,name=start_frame,json=startFrame,proto3" json:"start_frame,omitempty"`
	EndFrame     uint32                  `protobuf:"varint,5,opt,name=end_frame,json=endFrame,proto3" json:"end_frame,omitempty"`
	ThreadAmount uint32                  `protobuf:"varint,6,opt,name=threadAmount,proto3" json:"threadAmount,omitempty"`
	Completed    bool                    `protobuf:"varint,7,opt,name=completed,proto3" json:"completed,omitempty"`
	Reward       uint64                  `protobuf:"varint,8,opt,name=reward,proto3" json:"reward,omitempty"`
	Threads      []*VideoRenderingThread `protobuf:"bytes,9,rep,name=threads,proto3" json:"threads,omitempty"`
}

func (m *VideoRenderingTask) Reset()         { *m = VideoRenderingTask{} }
func (m *VideoRenderingTask) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingTask) ProtoMessage()    {}
func (*VideoRenderingTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{3}
}
func (m *VideoRenderingTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingTask.Merge(m, src)
}
func (m *VideoRenderingTask) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingTask) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingTask.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingTask proto.InternalMessageInfo

func (m *VideoRenderingTask) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *VideoRenderingTask) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *VideoRenderingTask) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *VideoRenderingTask) GetStartFrame() uint32 {
	if m != nil {
		return m.StartFrame
	}
	return 0
}

func (m *VideoRenderingTask) GetEndFrame() uint32 {
	if m != nil {
		return m.EndFrame
	}
	return 0
}

func (m *VideoRenderingTask) GetThreadAmount() uint32 {
	if m != nil {
		return m.ThreadAmount
	}
	return 0
}

func (m *VideoRenderingTask) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *VideoRenderingTask) GetReward() uint64 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *VideoRenderingTask) GetThreads() []*VideoRenderingThread {
	if m != nil {
		return m.Threads
	}
	return nil
}

// A Video Rendering Thread is the smallest unit of work for a Task.
// Workers will try to complete a thread as soon as possible to submit first a solution
type VideoRenderingThread struct {
	ThreadId    string                             `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	TaskId      string                             `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StartFrame  uint32                             `protobuf:"varint,3,opt,name=start_frame,json=startFrame,proto3" json:"start_frame,omitempty"`
	EndFrame    uint32                             `protobuf:"varint,4,opt,name=end_frame,json=endFrame,proto3" json:"end_frame,omitempty"`
	Completed   bool                               `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	Workers     []string                           `protobuf:"bytes,6,rep,name=workers,proto3" json:"workers,omitempty"`
	Solution    *VideoRenderingThread_Solution     `protobuf:"bytes,7,opt,name=solution,proto3" json:"solution,omitempty"`
	Validations []*VideoRenderingThread_Validation `protobuf:"bytes,8,rep,name=validations,proto3" json:"validations,omitempty"`
}

func (m *VideoRenderingThread) Reset()         { *m = VideoRenderingThread{} }
func (m *VideoRenderingThread) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingThread) ProtoMessage()    {}
func (*VideoRenderingThread) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{4}
}
func (m *VideoRenderingThread) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingThread) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingThread.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingThread) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingThread.Merge(m, src)
}
func (m *VideoRenderingThread) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingThread) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingThread.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingThread proto.InternalMessageInfo

func (m *VideoRenderingThread) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *VideoRenderingThread) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *VideoRenderingThread) GetStartFrame() uint32 {
	if m != nil {
		return m.StartFrame
	}
	return 0
}

func (m *VideoRenderingThread) GetEndFrame() uint32 {
	if m != nil {
		return m.EndFrame
	}
	return 0
}

func (m *VideoRenderingThread) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func (m *VideoRenderingThread) GetWorkers() []string {
	if m != nil {
		return m.Workers
	}
	return nil
}

func (m *VideoRenderingThread) GetSolution() *VideoRenderingThread_Solution {
	if m != nil {
		return m.Solution
	}
	return nil
}

func (m *VideoRenderingThread) GetValidations() []*VideoRenderingThread_Validation {
	if m != nil {
		return m.Validations
	}
	return nil
}

type VideoRenderingThread_Solution struct {
	ProposedBy string   `protobuf:"bytes,1,opt,name=proposed_by,json=proposedBy,proto3" json:"proposed_by,omitempty"`
	Hashes     []string `protobuf:"bytes,2,rep,name=hashes,proto3" json:"hashes,omitempty"`
	Files      string   `protobuf:"bytes,3,opt,name=files,proto3" json:"files,omitempty"`
}

func (m *VideoRenderingThread_Solution) Reset()         { *m = VideoRenderingThread_Solution{} }
func (m *VideoRenderingThread_Solution) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingThread_Solution) ProtoMessage()    {}
func (*VideoRenderingThread_Solution) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{4, 0}
}
func (m *VideoRenderingThread_Solution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingThread_Solution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingThread_Solution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingThread_Solution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingThread_Solution.Merge(m, src)
}
func (m *VideoRenderingThread_Solution) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingThread_Solution) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingThread_Solution.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingThread_Solution proto.InternalMessageInfo

func (m *VideoRenderingThread_Solution) GetProposedBy() string {
	if m != nil {
		return m.ProposedBy
	}
	return ""
}

func (m *VideoRenderingThread_Solution) GetHashes() []string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *VideoRenderingThread_Solution) GetFiles() string {
	if m != nil {
		return m.Files
	}
	return ""
}

type VideoRenderingThread_Validation struct {
	Validator   string `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	AmountFiles uint64 `protobuf:"varint,2,opt,name=amount_files,json=amountFiles,proto3" json:"amount_files,omitempty"`
	Valid       bool   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	IsReverse   bool   `protobuf:"varint,4,opt,name=is_reverse,json=isReverse,proto3" json:"is_reverse,omitempty"`
}

func (m *VideoRenderingThread_Validation) Reset()         { *m = VideoRenderingThread_Validation{} }
func (m *VideoRenderingThread_Validation) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingThread_Validation) ProtoMessage()    {}
func (*VideoRenderingThread_Validation) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{4, 1}
}
func (m *VideoRenderingThread_Validation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingThread_Validation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingThread_Validation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingThread_Validation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingThread_Validation.Merge(m, src)
}
func (m *VideoRenderingThread_Validation) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingThread_Validation) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingThread_Validation.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingThread_Validation proto.InternalMessageInfo

func (m *VideoRenderingThread_Validation) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

func (m *VideoRenderingThread_Validation) GetAmountFiles() uint64 {
	if m != nil {
		return m.AmountFiles
	}
	return 0
}

func (m *VideoRenderingThread_Validation) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *VideoRenderingThread_Validation) GetIsReverse() bool {
	if m != nil {
		return m.IsReverse
	}
	return false
}

// Stores information about the Video Rendering  task
type VideoRenderingTaskInfo struct {
	NextId uint64 `protobuf:"varint,1,opt,name=nextId,proto3" json:"nextId,omitempty"`
}

func (m *VideoRenderingTaskInfo) Reset()         { *m = VideoRenderingTaskInfo{} }
func (m *VideoRenderingTaskInfo) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingTaskInfo) ProtoMessage()    {}
func (*VideoRenderingTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{5}
}
func (m *VideoRenderingTaskInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingTaskInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingTaskInfo.Merge(m, src)
}
func (m *VideoRenderingTaskInfo) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingTaskInfo proto.InternalMessageInfo

func (m *VideoRenderingTaskInfo) GetNextId() uint64 {
	if m != nil {
		return m.NextId
	}
	return 0
}

// Stores the Video Rendering Task with the index
type IndexedVideoRenderingTask struct {
	Index              string             `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	VideoRenderingTask VideoRenderingTask `protobuf:"bytes,2,opt,name=videoRenderingTask,proto3" json:"videoRenderingTask"`
}

func (m *IndexedVideoRenderingTask) Reset()         { *m = IndexedVideoRenderingTask{} }
func (m *IndexedVideoRenderingTask) String() string { return proto.CompactTextString(m) }
func (*IndexedVideoRenderingTask) ProtoMessage()    {}
func (*IndexedVideoRenderingTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{6}
}
func (m *IndexedVideoRenderingTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndexedVideoRenderingTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndexedVideoRenderingTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndexedVideoRenderingTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexedVideoRenderingTask.Merge(m, src)
}
func (m *IndexedVideoRenderingTask) XXX_Size() int {
	return m.Size()
}
func (m *IndexedVideoRenderingTask) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexedVideoRenderingTask.DiscardUnknown(m)
}

var xxx_messageInfo_IndexedVideoRenderingTask proto.InternalMessageInfo

func (m *IndexedVideoRenderingTask) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *IndexedVideoRenderingTask) GetVideoRenderingTask() VideoRenderingTask {
	if m != nil {
		return m.VideoRenderingTask
	}
	return VideoRenderingTask{}
}

type VideoRenderingLogs struct {
	TaskId string                                  `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Logs   []*VideoRenderingLogs_VideoRenderingLog `protobuf:"bytes,2,rep,name=logs,proto3" json:"logs,omitempty"`
}

func (m *VideoRenderingLogs) Reset()         { *m = VideoRenderingLogs{} }
func (m *VideoRenderingLogs) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingLogs) ProtoMessage()    {}
func (*VideoRenderingLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{7}
}
func (m *VideoRenderingLogs) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingLogs.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingLogs.Merge(m, src)
}
func (m *VideoRenderingLogs) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingLogs.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingLogs proto.InternalMessageInfo

func (m *VideoRenderingLogs) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *VideoRenderingLogs) GetLogs() []*VideoRenderingLogs_VideoRenderingLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type VideoRenderingLogs_VideoRenderingLog struct {
	Id        string                                        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Log       string                                        `protobuf:"bytes,2,opt,name=log,proto3" json:"log,omitempty"`
	Timestamp int64                                         `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Severity  VideoRenderingLogs_VideoRenderingLog_SEVERITY `protobuf:"varint,4,opt,name=severity,proto3,enum=janction.videoRendering.v1.VideoRenderingLogs_VideoRenderingLog_SEVERITY" json:"severity,omitempty"`
}

func (m *VideoRenderingLogs_VideoRenderingLog) Reset()         { *m = VideoRenderingLogs_VideoRenderingLog{} }
func (m *VideoRenderingLogs_VideoRenderingLog) String() string { return proto.CompactTextString(m) }
func (*VideoRenderingLogs_VideoRenderingLog) ProtoMessage()    {}
func (*VideoRenderingLogs_VideoRenderingLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_48dc248d3c391ada, []int{7, 0}
}
func (m *VideoRenderingLogs_VideoRenderingLog) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VideoRenderingLogs_VideoRenderingLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VideoRenderingLogs_VideoRenderingLog.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VideoRenderingLogs_VideoRenderingLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoRenderingLogs_VideoRenderingLog.Merge(m, src)
}
func (m *VideoRenderingLogs_VideoRenderingLog) XXX_Size() int {
	return m.Size()
}
func (m *VideoRenderingLogs_VideoRenderingLog) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoRenderingLogs_VideoRenderingLog.DiscardUnknown(m)
}

var xxx_messageInfo_VideoRenderingLogs_VideoRenderingLog proto.InternalMessageInfo

func (m *VideoRenderingLogs_VideoRenderingLog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VideoRenderingLogs_VideoRenderingLog) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

func (m *VideoRenderingLogs_VideoRenderingLog) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VideoRenderingLogs_VideoRenderingLog) GetSeverity() VideoRenderingLogs_VideoRenderingLog_SEVERITY {
	if m != nil {
		return m.Severity
	}
	return VideoRenderingLogs_VideoRenderingLog_INFO
}

func init() {
	proto.RegisterEnum("janction.videoRendering.v1.VideoRenderingLogs_VideoRenderingLog_SEVERITY", VideoRenderingLogs_VideoRenderingLog_SEVERITY_name, VideoRenderingLogs_VideoRenderingLog_SEVERITY_value)
	proto.RegisterType((*Params)(nil), "janction.videoRendering.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "janction.videoRendering.v1.GenesisState")
	proto.RegisterType((*Worker)(nil), "janction.videoRendering.v1.Worker")
	proto.RegisterType((*Worker_Reputation)(nil), "janction.videoRendering.v1.Worker.Reputation")
	proto.RegisterType((*VideoRenderingTask)(nil), "janction.videoRendering.v1.VideoRenderingTask")
	proto.RegisterType((*VideoRenderingThread)(nil), "janction.videoRendering.v1.VideoRenderingThread")
	proto.RegisterType((*VideoRenderingThread_Solution)(nil), "janction.videoRendering.v1.VideoRenderingThread.Solution")
	proto.RegisterType((*VideoRenderingThread_Validation)(nil), "janction.videoRendering.v1.VideoRenderingThread.Validation")
	proto.RegisterType((*VideoRenderingTaskInfo)(nil), "janction.videoRendering.v1.VideoRenderingTaskInfo")
	proto.RegisterType((*IndexedVideoRenderingTask)(nil), "janction.videoRendering.v1.IndexedVideoRenderingTask")
	proto.RegisterType((*VideoRenderingLogs)(nil), "janction.videoRendering.v1.VideoRenderingLogs")
	proto.RegisterType((*VideoRenderingLogs_VideoRenderingLog)(nil), "janction.videoRendering.v1.VideoRenderingLogs.VideoRenderingLog")
}

func init() {
	proto.RegisterFile("janction/videoRendering/v1/types.proto", fileDescriptor_48dc248d3c391ada)
}

var fileDescriptor_48dc248d3c391ada = []byte{
	// 1042 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x4d, 0x6f, 0x1b, 0x45,
	0x18, 0xce, 0xfa, 0x73, 0xfd, 0xba, 0x29, 0x61, 0x14, 0xc2, 0xd6, 0x80, 0x63, 0xf6, 0x50, 0xf9,
	0x40, 0xd7, 0xa9, 0x11, 0xa0, 0x0a, 0x0e, 0x4d, 0xaa, 0x04, 0x19, 0x4a, 0x8b, 0xc6, 0x69, 0x10,
	0x48, 0x68, 0xb5, 0xf1, 0x4c, 0x9c, 0x25, 0xf6, 0xce, 0x32, 0x33, 0x4e, 0xeb, 0x0b, 0xbf, 0x80,
	0x03, 0x37, 0x2e, 0xfc, 0x0c, 0x7e, 0x44, 0x8f, 0x15, 0x27, 0xc4, 0x01, 0xa1, 0xe4, 0xc2, 0x85,
	0x5f, 0xc0, 0x01, 0x34, 0x1f, 0x6b, 0xd7, 0x71, 0xec, 0x10, 0x71, 0xdb, 0xf7, 0x63, 0x9e, 0xe7,
	0x9d, 0x67, 0xde, 0x77, 0x66, 0xe1, 0xf6, 0x37, 0x51, 0xd2, 0x93, 0x31, 0x4b, 0x5a, 0xa7, 0x31,
	0xa1, 0x0c, 0xd3, 0x84, 0x50, 0x1e, 0x27, 0xfd, 0xd6, 0xe9, 0xdd, 0x96, 0x1c, 0xa7, 0x54, 0x04,
	0x29, 0x67, 0x92, 0xa1, 0x5a, 0x96, 0x17, 0xcc, 0xe6, 0x05, 0xa7, 0x77, 0x6b, 0xb7, 0x7a, 0x4c,
	0x0c, 0x99, 0x08, 0x75, 0x66, 0xcb, 0x18, 0x66, 0x59, 0x6d, 0xbd, 0xcf, 0xfa, 0xcc, 0xf8, 0xd5,
	0x97, 0xf5, 0x6e, 0xf6, 0x19, 0xeb, 0x0f, 0x68, 0x4b, 0x5b, 0x87, 0xa3, 0xa3, 0x96, 0x8c, 0x87,
	0x54, 0xc8, 0x68, 0x98, 0x9a, 0x04, 0x7f, 0x1b, 0x4a, 0x9f, 0x47, 0x3c, 0x1a, 0x0a, 0xf4, 0x01,
	0x78, 0x9a, 0x30, 0xe4, 0x19, 0x63, 0x78, 0x42, 0xc7, 0x61, 0x12, 0x0d, 0xa9, 0xe7, 0x34, 0x9c,
	0x66, 0x05, 0xbf, 0x36, 0x5b, 0xd0, 0xa7, 0x74, 0xfc, 0x28, 0x1a, 0x52, 0xff, 0xef, 0x1c, 0xdc,
	0xf8, 0x98, 0x26, 0x54, 0xc4, 0xa2, 0x2b, 0x23, 0x49, 0xd1, 0x7d, 0x28, 0xa5, 0x1a, 0x53, 0xaf,
	0xab, 0xb6, 0xfd, 0x60, 0xf1, 0x96, 0x02, 0xc3, 0xbe, 0x53, 0x78, 0xfe, 0xfb, 0xe6, 0x0a, 0xb6,
	0xeb, 0x50, 0x0a, 0x1b, 0xb3, 0x99, 0xfb, 0x91, 0x38, 0xe9, 0x24, 0x47, 0xcc, 0xcb, 0x6b, 0xc4,
	0xf6, 0x32, 0xc4, 0x83, 0x4b, 0x57, 0x5a, 0x86, 0x05, 0xb8, 0x48, 0x5c, 0xc6, 0xf8, 0x30, 0x16,
	0xd2, 0x2b, 0x34, 0xf2, 0xcd, 0x6a, 0xfb, 0xbd, 0x65, 0x8c, 0x9d, 0x84, 0xd0, 0x67, 0x94, 0xcc,
	0x13, 0x2f, 0x26, 0x55, 0xd0, 0x68, 0x07, 0xca, 0x4f, 0x19, 0x3f, 0xa1, 0x5c, 0x78, 0x45, 0xcd,
	0xb2, 0x54, 0xa9, 0x2f, 0x74, 0xaa, 0x85, 0xcc, 0x16, 0xfa, 0xff, 0xe4, 0xa0, 0x64, 0x22, 0xa8,
	0x0d, 0xe5, 0x88, 0x10, 0x4e, 0x85, 0x11, 0xbe, 0xb2, 0xe3, 0xfd, 0xf2, 0xf3, 0x9d, 0x75, 0xdb,
	0x25, 0xdb, 0x26, 0xd2, 0x95, 0x0a, 0x0e, 0x67, 0x89, 0xe8, 0x33, 0x00, 0x4e, 0xd3, 0x91, 0x8c,
	0x14, 0xa9, 0x55, 0xf7, 0xce, 0xd5, 0x55, 0x04, 0x78, 0xb2, 0x08, 0xbf, 0x04, 0x80, 0x3c, 0x28,
	0xd3, 0x24, 0x3a, 0x1c, 0x50, 0xe2, 0x15, 0x1a, 0x4e, 0xd3, 0xc5, 0x99, 0x89, 0x6e, 0xc3, 0x2b,
	0xbd, 0x11, 0xe7, 0x34, 0x91, 0xa1, 0x8c, 0xc4, 0x49, 0x18, 0x13, 0xaf, 0xa8, 0xbb, 0x6a, 0xd5,
	0xba, 0xf5, 0x51, 0x10, 0xb4, 0x05, 0xeb, 0x93, 0xbc, 0x63, 0x4e, 0x23, 0x12, 0xc6, 0x4a, 0x5d,
	0xaf, 0xd4, 0x70, 0x9a, 0xab, 0x18, 0x65, 0xc9, 0x3a, 0xa4, 0x75, 0xaf, 0x7d, 0x07, 0x80, 0x67,
	0x2a, 0x10, 0x32, 0xea, 0x9d, 0x50, 0xa2, 0x45, 0x28, 0xe0, 0xcc, 0x44, 0x1b, 0x50, 0x4a, 0x59,
	0x9c, 0x48, 0xe1, 0xe5, 0x1a, 0x4e, 0x33, 0x8f, 0xad, 0x85, 0x1a, 0x50, 0x3d, 0x8d, 0x06, 0x31,
	0xd1, 0xeb, 0x85, 0xd6, 0x60, 0x15, 0xbf, 0xec, 0x42, 0x6f, 0x42, 0x45, 0xb0, 0xc1, 0xc8, 0xc4,
	0x0b, 0x3a, 0x3e, 0x75, 0xf8, 0xbf, 0xe5, 0x00, 0xcd, 0x1f, 0xbd, 0xa2, 0x93, 0x7a, 0x4b, 0x76,
	0x7a, 0xac, 0x85, 0xde, 0x87, 0x0a, 0xa7, 0xdf, 0x8e, 0xa8, 0x90, 0x94, 0xeb, 0x4a, 0x96, 0x9d,
	0xd3, 0x34, 0x15, 0xad, 0x41, 0xbe, 0x17, 0x13, 0x5d, 0x5e, 0x05, 0xab, 0x4f, 0xb4, 0x09, 0x55,
	0x21, 0x23, 0x2e, 0xc3, 0x23, 0xae, 0x86, 0xd4, 0x14, 0x06, 0xda, 0xb5, 0xa7, 0x3c, 0xe8, 0x0d,
	0xa8, 0xd0, 0x84, 0xd8, 0x70, 0x51, 0x87, 0x5d, 0x9a, 0x10, 0x13, 0xf4, 0xe1, 0x86, 0x11, 0x78,
	0x7b, 0xc8, 0x46, 0x89, 0xb4, 0x02, 0xcf, 0xf8, 0xd4, 0xc6, 0x7b, 0x6c, 0x98, 0x0e, 0xa8, 0xa4,
	0xc4, 0x2b, 0xeb, 0x03, 0x9d, 0x3a, 0xd4, 0x0e, 0x39, 0x7d, 0x1a, 0x71, 0xe2, 0xb9, 0x5a, 0x69,
	0x6b, 0xa1, 0x4f, 0xa0, 0x6c, 0x50, 0x84, 0x57, 0xd1, 0x6d, 0xbd, 0x75, 0x8d, 0x71, 0xd5, 0x0b,
	0x71, 0x06, 0xe0, 0x7f, 0x5f, 0x84, 0xf5, 0xcb, 0x32, 0xd4, 0xde, 0xb2, 0xfe, 0xc8, 0x14, 0x76,
	0x8d, 0xa3, 0x43, 0xd0, 0xeb, 0x50, 0xce, 0x9a, 0x2c, 0x37, 0x23, 0xfe, 0x05, 0xc9, 0xf2, 0xcb,
	0x25, 0x2b, 0x5c, 0x90, 0x6c, 0x46, 0x8e, 0xe2, 0x45, 0x39, 0xbc, 0xe9, 0x34, 0x97, 0x1a, 0xf9,
	0x66, 0x65, 0x32, 0xa3, 0xe8, 0x09, 0xb8, 0x59, 0xbb, 0x68, 0x15, 0xab, 0xed, 0x7b, 0xd7, 0x55,
	0x24, 0xe8, 0x5a, 0x00, 0x3c, 0x81, 0x42, 0x5f, 0xcf, 0x36, 0xae, 0xab, 0xb5, 0xfe, 0xf0, 0xda,
	0xc8, 0x07, 0x13, 0x8c, 0x99, 0xae, 0xaf, 0x09, 0x70, 0x33, 0x52, 0x74, 0x0f, 0xaa, 0x29, 0x67,
	0x29, 0x13, 0x94, 0x84, 0x87, 0xe3, 0x2b, 0xaf, 0x17, 0xc8, 0x92, 0x77, 0xc6, 0xaa, 0x4b, 0x8e,
	0x23, 0x71, 0x4c, 0xd5, 0xd8, 0x29, 0x55, 0xac, 0x85, 0xd6, 0xa1, 0x78, 0x14, 0x0f, 0xa8, 0xb0,
	0x1d, 0x6d, 0x8c, 0xda, 0x4f, 0x0e, 0xc0, 0xb4, 0x20, 0x35, 0x2c, 0xb6, 0x24, 0xc6, 0xaf, 0x64,
	0x9d, 0xa6, 0xa2, 0xb7, 0xe1, 0x46, 0xa4, 0x5b, 0x38, 0x34, 0x1c, 0x39, 0xdd, 0xa0, 0x55, 0xe3,
	0xdb, 0x53, 0x2e, 0xc5, 0xaf, 0xf3, 0x35, 0xbf, 0x8b, 0x8d, 0x81, 0xde, 0x02, 0x88, 0x45, 0xc8,
	0xe9, 0x29, 0xe5, 0x82, 0xda, 0x3b, 0xac, 0x12, 0x0b, 0x6c, 0x1c, 0xfe, 0x16, 0x6c, 0x5c, 0xfe,
	0xbc, 0xa8, 0x6d, 0x26, 0xf4, 0x99, 0xec, 0x64, 0xd7, 0x8e, 0xb5, 0xfc, 0x1f, 0x1d, 0xb8, 0xb5,
	0xf0, 0x7d, 0x50, 0x45, 0x98, 0xeb, 0xcd, 0x74, 0xb0, 0x31, 0x10, 0x01, 0x34, 0xff, 0x62, 0xe8,
	0x3d, 0x54, 0xdb, 0xc1, 0xf5, 0x9e, 0x3e, 0xfb, 0x5c, 0x5c, 0x82, 0xe7, 0xff, 0x35, 0x77, 0x6f,
	0x3d, 0x64, 0x7d, 0xb1, 0xf0, 0xde, 0xda, 0x87, 0xc2, 0x80, 0xf5, 0xcd, 0x29, 0x56, 0xdb, 0xf7,
	0xff, 0x7b, 0x19, 0x0a, 0x75, 0xde, 0x85, 0x35, 0x5a, 0xed, 0x4f, 0x07, 0x5e, 0x9d, 0x8b, 0xa1,
	0x9b, 0x90, 0x9b, 0x4c, 0x75, 0x2e, 0x26, 0xea, 0xee, 0x1b, 0xb0, 0xbe, 0x9d, 0x65, 0xf5, 0xa9,
	0x46, 0x71, 0xf2, 0x2b, 0xa3, 0x4f, 0x30, 0x8f, 0xa7, 0x0e, 0x44, 0xc1, 0x15, 0xea, 0xc4, 0x62,
	0x39, 0xd6, 0x67, 0x78, 0xb3, 0xdd, 0xf9, 0xbf, 0xf5, 0x06, 0xdd, 0xdd, 0x83, 0x5d, 0xdc, 0xd9,
	0xff, 0x12, 0x4f, 0xa0, 0xfd, 0x77, 0xc0, 0xcd, 0xbc, 0xc8, 0x85, 0x42, 0xe7, 0xd1, 0xde, 0xe3,
	0xb5, 0x15, 0x54, 0x85, 0x72, 0xf7, 0xc9, 0x83, 0x07, 0xbb, 0xdd, 0xee, 0x9a, 0x83, 0x2a, 0x50,
	0xdc, 0xc5, 0xf8, 0x31, 0x5e, 0xcb, 0xed, 0x7c, 0xf4, 0xfc, 0xac, 0xee, 0xbc, 0x38, 0xab, 0x3b,
	0x7f, 0x9c, 0xd5, 0x9d, 0x1f, 0xce, 0xeb, 0x2b, 0x2f, 0xce, 0xeb, 0x2b, 0xbf, 0x9e, 0xd7, 0x57,
	0xbe, 0xf2, 0xfb, 0xb1, 0x3c, 0x1e, 0x1d, 0x06, 0x3d, 0x36, 0x6c, 0x2d, 0xf8, 0x4b, 0x3c, 0x2c,
	0xe9, 0xff, 0xb5, 0x77, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x64, 0x45, 0xb4, 0xc4, 0x47, 0x0a,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.VideoRenderingKeyName) > 0 {
		i -= len(m.VideoRenderingKeyName)
		copy(dAtA[i:], m.VideoRenderingKeyName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VideoRenderingKeyName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Workers) > 0 {
		for iNdEx := len(m.Workers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Workers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.VideoRenderingTaskList) > 0 {
		for iNdEx := len(m.VideoRenderingTaskList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VideoRenderingTaskList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size, err := m.VideoRenderingTaskInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Worker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Worker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Worker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentThreadIndex != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CurrentThreadIndex))
		i--
		dAtA[i] = 0x30
	}
	if len(m.CurrentTaskId) > 0 {
		i -= len(m.CurrentTaskId)
		copy(dAtA[i:], m.CurrentTaskId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CurrentTaskId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Reputation != nil {
		{
			size, err := m.Reputation.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Worker_Reputation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Worker_Reputation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Worker_Reputation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Solutions != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Solutions))
		i--
		dAtA[i] = 0x20
	}
	if m.Validations != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Validations))
		i--
		dAtA[i] = 0x18
	}
	if m.Points != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Points))
		i--
		dAtA[i] = 0x10
	}
	if m.Stacked != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Stacked))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Threads) > 0 {
		for iNdEx := len(m.Threads) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Threads[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.Reward != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Reward))
		i--
		dAtA[i] = 0x40
	}
	if m.Completed {
		i--
		if m.Completed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.ThreadAmount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ThreadAmount))
		i--
		dAtA[i] = 0x30
	}
	if m.EndFrame != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EndFrame))
		i--
		dAtA[i] = 0x28
	}
	if m.StartFrame != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StartFrame))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingThread) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingThread) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingThread) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Validations) > 0 {
		for iNdEx := len(m.Validations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Solution != nil {
		{
			size, err := m.Solution.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTypes(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Workers) > 0 {
		for iNdEx := len(m.Workers) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Workers[iNdEx])
			copy(dAtA[i:], m.Workers[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Workers[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if m.Completed {
		i--
		if m.Completed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.EndFrame != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.EndFrame))
		i--
		dAtA[i] = 0x20
	}
	if m.StartFrame != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.StartFrame))
		i--
		dAtA[i] = 0x18
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingThread_Solution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingThread_Solution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingThread_Solution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Files) > 0 {
		i -= len(m.Files)
		copy(dAtA[i:], m.Files)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Files)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hashes) > 0 {
		for iNdEx := len(m.Hashes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Hashes[iNdEx])
			copy(dAtA[i:], m.Hashes[iNdEx])
			i = encodeVarintTypes(dAtA, i, uint64(len(m.Hashes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ProposedBy) > 0 {
		i -= len(m.ProposedBy)
		copy(dAtA[i:], m.ProposedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.ProposedBy)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingThread_Validation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingThread_Validation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingThread_Validation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsReverse {
		i--
		if m.IsReverse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Valid {
		i--
		if m.Valid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.AmountFiles != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AmountFiles))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Validator) > 0 {
		i -= len(m.Validator)
		copy(dAtA[i:], m.Validator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Validator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingTaskInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingTaskInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingTaskInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NextId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.NextId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *IndexedVideoRenderingTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndexedVideoRenderingTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndexedVideoRenderingTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.VideoRenderingTask.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingLogs) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingLogs) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingLogs) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Logs) > 0 {
		for iNdEx := len(m.Logs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Logs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VideoRenderingLogs_VideoRenderingLog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VideoRenderingLogs_VideoRenderingLog) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VideoRenderingLogs_VideoRenderingLog) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Severity != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Severity))
		i--
		dAtA[i] = 0x20
	}
	if m.Timestamp != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Log) > 0 {
		i -= len(m.Log)
		copy(dAtA[i:], m.Log)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Log)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.VideoRenderingKeyName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovTypes(uint64(l))
	l = m.VideoRenderingTaskInfo.Size()
	n += 1 + l + sovTypes(uint64(l))
	if len(m.VideoRenderingTaskList) > 0 {
		for _, e := range m.VideoRenderingTaskList {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if len(m.Workers) > 0 {
		for _, e := range m.Workers {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *Worker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Reputation != nil {
		l = m.Reputation.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	l = len(m.CurrentTaskId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.CurrentThreadIndex != 0 {
		n += 1 + sovTypes(uint64(m.CurrentThreadIndex))
	}
	return n
}

func (m *Worker_Reputation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stacked != 0 {
		n += 1 + sovTypes(uint64(m.Stacked))
	}
	if m.Points != 0 {
		n += 1 + sovTypes(uint64(m.Points))
	}
	if m.Validations != 0 {
		n += 1 + sovTypes(uint64(m.Validations))
	}
	if m.Solutions != 0 {
		n += 1 + sovTypes(uint64(m.Solutions))
	}
	return n
}

func (m *VideoRenderingTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.StartFrame != 0 {
		n += 1 + sovTypes(uint64(m.StartFrame))
	}
	if m.EndFrame != 0 {
		n += 1 + sovTypes(uint64(m.EndFrame))
	}
	if m.ThreadAmount != 0 {
		n += 1 + sovTypes(uint64(m.ThreadAmount))
	}
	if m.Completed {
		n += 2
	}
	if m.Reward != 0 {
		n += 1 + sovTypes(uint64(m.Reward))
	}
	if len(m.Threads) > 0 {
		for _, e := range m.Threads {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *VideoRenderingThread) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.StartFrame != 0 {
		n += 1 + sovTypes(uint64(m.StartFrame))
	}
	if m.EndFrame != 0 {
		n += 1 + sovTypes(uint64(m.EndFrame))
	}
	if m.Completed {
		n += 2
	}
	if len(m.Workers) > 0 {
		for _, s := range m.Workers {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Solution != nil {
		l = m.Solution.Size()
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Validations) > 0 {
		for _, e := range m.Validations {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *VideoRenderingThread_Solution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ProposedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Hashes) > 0 {
		for _, s := range m.Hashes {
			l = len(s)
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	l = len(m.Files)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *VideoRenderingThread_Validation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Validator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AmountFiles != 0 {
		n += 1 + sovTypes(uint64(m.AmountFiles))
	}
	if m.Valid {
		n += 2
	}
	if m.IsReverse {
		n += 2
	}
	return n
}

func (m *VideoRenderingTaskInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NextId != 0 {
		n += 1 + sovTypes(uint64(m.NextId))
	}
	return n
}

func (m *IndexedVideoRenderingTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.VideoRenderingTask.Size()
	n += 1 + l + sovTypes(uint64(l))
	return n
}

func (m *VideoRenderingLogs) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if len(m.Logs) > 0 {
		for _, e := range m.Logs {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *VideoRenderingLogs_VideoRenderingLog) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Log)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTypes(uint64(m.Timestamp))
	}
	if m.Severity != 0 {
		n += 1 + sovTypes(uint64(m.Severity))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoRenderingKeyName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VideoRenderingKeyName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoRenderingTaskInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VideoRenderingTaskInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoRenderingTaskList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VideoRenderingTaskList = append(m.VideoRenderingTaskList, IndexedVideoRenderingTask{})
			if err := m.VideoRenderingTaskList[len(m.VideoRenderingTaskList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Workers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Workers = append(m.Workers, Worker{})
			if err := m.Workers[len(m.Workers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Worker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Worker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Worker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reputation", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Reputation == nil {
				m.Reputation = &Worker_Reputation{}
			}
			if err := m.Reputation.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentTaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentTaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentThreadIndex", wireType)
			}
			m.CurrentThreadIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentThreadIndex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Worker_Reputation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Reputation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Reputation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stacked", wireType)
			}
			m.Stacked = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stacked |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Points", wireType)
			}
			m.Points = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Points |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validations", wireType)
			}
			m.Validations = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Validations |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solutions", wireType)
			}
			m.Solutions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Solutions |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VideoRenderingTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VideoRenderingTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartFrame", wireType)
			}
			m.StartFrame = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartFrame |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndFrame", wireType)
			}
			m.EndFrame = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndFrame |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadAmount", wireType)
			}
			m.ThreadAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ThreadAmount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Completed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Completed = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			m.Reward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reward |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threads", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Threads = append(m.Threads, &VideoRenderingThread{})
			if err := m.Threads[len(m.Threads)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingThread) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VideoRenderingThread: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VideoRenderingThread: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartFrame", wireType)
			}
			m.StartFrame = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartFrame |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndFrame", wireType)
			}
			m.EndFrame = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndFrame |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Completed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Completed = bool(v != 0)
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Workers", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Workers = append(m.Workers, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solution", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Solution == nil {
				m.Solution = &VideoRenderingThread_Solution{}
			}
			if err := m.Solution.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validations = append(m.Validations, &VideoRenderingThread_Validation{})
			if err := m.Validations[len(m.Validations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingThread_Solution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Solution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Solution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hashes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hashes = append(m.Hashes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Files", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Files = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingThread_Validation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountFiles", wireType)
			}
			m.AmountFiles = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AmountFiles |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Valid = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsReverse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsReverse = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingTaskInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VideoRenderingTaskInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VideoRenderingTaskInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextId", wireType)
			}
			m.NextId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IndexedVideoRenderingTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndexedVideoRenderingTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndexedVideoRenderingTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VideoRenderingTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VideoRenderingTask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingLogs) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VideoRenderingLogs: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VideoRenderingLogs: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Logs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Logs = append(m.Logs, &VideoRenderingLogs_VideoRenderingLog{})
			if err := m.Logs[len(m.Logs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VideoRenderingLogs_VideoRenderingLog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VideoRenderingLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VideoRenderingLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Log", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Log = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Severity", wireType)
			}
			m.Severity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Severity |= VideoRenderingLogs_VideoRenderingLog_SEVERITY(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
