ipfs_seeds:
  - "/ip4/3.19.120.0/tcp/4001/ipfs/QmUkq5CA4biZZuez9gyC6uXheGMSNWyEEDB4VBRDbHrqJX"
  - "/ip4/33.16.54.77/tcp/4001/ipfs/12D3KooWLjmDR6A4TLT3XrvffVPPabgdctdtm38aCvt3d4zU3HWL"
  - "/ip4/3.149.24.64/tcp/4001/ipfs/12D3KooWB4nSVSgDUBVW5u2NfesDf14ptNsyEDo9qAjRmztrKsLt"
  - /ip4/192.168.1.227/tcp/4001/ipfs/12D3KooWFnwvXxhWBerC74or7c3FMDHNPEbHoWRmJ2rGk8So7dkk
  