// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: janction/videoRendering/v1/tx.proto

package videoRendering

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCreateGame defines the Msg/CreateGame request type.
type MsgCreateVideoRenderingTask struct {
	// creator is the message sender.
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Cid        string `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	StartFrame uint32 `protobuf:"varint,3,opt,name=startFrame,proto3" json:"startFrame,omitempty"`
	EndFrame   uint32 `protobuf:"varint,4,opt,name=endFrame,proto3" json:"endFrame,omitempty"`
	Threads    uint32 `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	Reward     uint64 `protobuf:"varint,6,opt,name=reward,proto3" json:"reward,omitempty"`
}

func (m *MsgCreateVideoRenderingTask) Reset()         { *m = MsgCreateVideoRenderingTask{} }
func (m *MsgCreateVideoRenderingTask) String() string { return proto.CompactTextString(m) }
func (*MsgCreateVideoRenderingTask) ProtoMessage()    {}
func (*MsgCreateVideoRenderingTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{0}
}
func (m *MsgCreateVideoRenderingTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateVideoRenderingTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateVideoRenderingTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateVideoRenderingTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateVideoRenderingTask.Merge(m, src)
}
func (m *MsgCreateVideoRenderingTask) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateVideoRenderingTask) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateVideoRenderingTask.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateVideoRenderingTask proto.InternalMessageInfo

func (m *MsgCreateVideoRenderingTask) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateVideoRenderingTask) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *MsgCreateVideoRenderingTask) GetStartFrame() uint32 {
	if m != nil {
		return m.StartFrame
	}
	return 0
}

func (m *MsgCreateVideoRenderingTask) GetEndFrame() uint32 {
	if m != nil {
		return m.EndFrame
	}
	return 0
}

func (m *MsgCreateVideoRenderingTask) GetThreads() uint32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *MsgCreateVideoRenderingTask) GetReward() uint64 {
	if m != nil {
		return m.Reward
	}
	return 0
}

// MsgCreateGameResponse defines the Msg/CreateGame response type.
type MsgCreateVideoRenderingTaskResponse struct {
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (m *MsgCreateVideoRenderingTaskResponse) Reset()         { *m = MsgCreateVideoRenderingTaskResponse{} }
func (m *MsgCreateVideoRenderingTaskResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateVideoRenderingTaskResponse) ProtoMessage()    {}
func (*MsgCreateVideoRenderingTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{1}
}
func (m *MsgCreateVideoRenderingTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateVideoRenderingTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateVideoRenderingTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateVideoRenderingTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateVideoRenderingTaskResponse.Merge(m, src)
}
func (m *MsgCreateVideoRenderingTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateVideoRenderingTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateVideoRenderingTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateVideoRenderingTaskResponse proto.InternalMessageInfo

func (m *MsgCreateVideoRenderingTaskResponse) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type MsgAddWorker struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PublicIp string `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
}

func (m *MsgAddWorker) Reset()         { *m = MsgAddWorker{} }
func (m *MsgAddWorker) String() string { return proto.CompactTextString(m) }
func (*MsgAddWorker) ProtoMessage()    {}
func (*MsgAddWorker) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{2}
}
func (m *MsgAddWorker) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddWorker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddWorker.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddWorker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddWorker.Merge(m, src)
}
func (m *MsgAddWorker) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddWorker) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddWorker.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddWorker proto.InternalMessageInfo

func (m *MsgAddWorker) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgAddWorker) GetPublicIp() string {
	if m != nil {
		return m.PublicIp
	}
	return ""
}

type MsgAddWorkerResponse struct {
}

func (m *MsgAddWorkerResponse) Reset()         { *m = MsgAddWorkerResponse{} }
func (m *MsgAddWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddWorkerResponse) ProtoMessage()    {}
func (*MsgAddWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{3}
}
func (m *MsgAddWorkerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddWorkerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddWorkerResponse.Merge(m, src)
}
func (m *MsgAddWorkerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddWorkerResponse proto.InternalMessageInfo

type MsgSubscribeWorkerToTask struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TaskId  string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
}

func (m *MsgSubscribeWorkerToTask) Reset()         { *m = MsgSubscribeWorkerToTask{} }
func (m *MsgSubscribeWorkerToTask) String() string { return proto.CompactTextString(m) }
func (*MsgSubscribeWorkerToTask) ProtoMessage()    {}
func (*MsgSubscribeWorkerToTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{4}
}
func (m *MsgSubscribeWorkerToTask) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubscribeWorkerToTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubscribeWorkerToTask.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubscribeWorkerToTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubscribeWorkerToTask.Merge(m, src)
}
func (m *MsgSubscribeWorkerToTask) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubscribeWorkerToTask) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubscribeWorkerToTask.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubscribeWorkerToTask proto.InternalMessageInfo

func (m *MsgSubscribeWorkerToTask) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgSubscribeWorkerToTask) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type MsgSubscribeWorkerToTaskResponse struct {
	ThreadId string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
}

func (m *MsgSubscribeWorkerToTaskResponse) Reset()         { *m = MsgSubscribeWorkerToTaskResponse{} }
func (m *MsgSubscribeWorkerToTaskResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubscribeWorkerToTaskResponse) ProtoMessage()    {}
func (*MsgSubscribeWorkerToTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{5}
}
func (m *MsgSubscribeWorkerToTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubscribeWorkerToTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubscribeWorkerToTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubscribeWorkerToTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubscribeWorkerToTaskResponse.Merge(m, src)
}
func (m *MsgSubscribeWorkerToTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubscribeWorkerToTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubscribeWorkerToTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubscribeWorkerToTaskResponse proto.InternalMessageInfo

func (m *MsgSubscribeWorkerToTaskResponse) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

// Msg to Propose a solution to an specific thread
// Actual solution is a map of hashes
type MsgProposeSolution struct {
	Creator  string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TaskId   string   `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ThreadId string   `protobuf:"bytes,3,opt,name=threadId,proto3" json:"threadId,omitempty"`
	Solution []string `protobuf:"bytes,4,rep,name=solution,proto3" json:"solution,omitempty"`
}

func (m *MsgProposeSolution) Reset()         { *m = MsgProposeSolution{} }
func (m *MsgProposeSolution) String() string { return proto.CompactTextString(m) }
func (*MsgProposeSolution) ProtoMessage()    {}
func (*MsgProposeSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{6}
}
func (m *MsgProposeSolution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProposeSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProposeSolution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProposeSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeSolution.Merge(m, src)
}
func (m *MsgProposeSolution) XXX_Size() int {
	return m.Size()
}
func (m *MsgProposeSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeSolution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeSolution proto.InternalMessageInfo

func (m *MsgProposeSolution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgProposeSolution) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *MsgProposeSolution) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *MsgProposeSolution) GetSolution() []string {
	if m != nil {
		return m.Solution
	}
	return nil
}

// no response needed to a proposed solution
type MsgProposeSolutionResponse struct {
}

func (m *MsgProposeSolutionResponse) Reset()         { *m = MsgProposeSolutionResponse{} }
func (m *MsgProposeSolutionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgProposeSolutionResponse) ProtoMessage()    {}
func (*MsgProposeSolutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{7}
}
func (m *MsgProposeSolutionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgProposeSolutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgProposeSolutionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgProposeSolutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgProposeSolutionResponse.Merge(m, src)
}
func (m *MsgProposeSolutionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgProposeSolutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgProposeSolutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgProposeSolutionResponse proto.InternalMessageInfo

type MsgSubmitValidation struct {
	Creator     string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TaskId      string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ThreadId    string `protobuf:"bytes,3,opt,name=threadId,proto3" json:"threadId,omitempty"`
	FilesAmount uint64 `protobuf:"varint,4,opt,name=filesAmount,proto3" json:"filesAmount,omitempty"`
	Valid       bool   `protobuf:"varint,5,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (m *MsgSubmitValidation) Reset()         { *m = MsgSubmitValidation{} }
func (m *MsgSubmitValidation) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitValidation) ProtoMessage()    {}
func (*MsgSubmitValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{8}
}
func (m *MsgSubmitValidation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitValidation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitValidation.Merge(m, src)
}
func (m *MsgSubmitValidation) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitValidation.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitValidation proto.InternalMessageInfo

func (m *MsgSubmitValidation) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitValidation) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *MsgSubmitValidation) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *MsgSubmitValidation) GetFilesAmount() uint64 {
	if m != nil {
		return m.FilesAmount
	}
	return 0
}

func (m *MsgSubmitValidation) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

type MsgSubmitValidationResponse struct {
}

func (m *MsgSubmitValidationResponse) Reset()         { *m = MsgSubmitValidationResponse{} }
func (m *MsgSubmitValidationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitValidationResponse) ProtoMessage()    {}
func (*MsgSubmitValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{9}
}
func (m *MsgSubmitValidationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitValidationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitValidationResponse.Merge(m, src)
}
func (m *MsgSubmitValidationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitValidationResponse proto.InternalMessageInfo

type MsgSubmitSolution struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TaskId   string `protobuf:"bytes,2,opt,name=taskId,proto3" json:"taskId,omitempty"`
	ThreadId string `protobuf:"bytes,3,opt,name=threadId,proto3" json:"threadId,omitempty"`
	Cid      string `protobuf:"bytes,4,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (m *MsgSubmitSolution) Reset()         { *m = MsgSubmitSolution{} }
func (m *MsgSubmitSolution) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitSolution) ProtoMessage()    {}
func (*MsgSubmitSolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{10}
}
func (m *MsgSubmitSolution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitSolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitSolution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitSolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitSolution.Merge(m, src)
}
func (m *MsgSubmitSolution) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitSolution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitSolution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitSolution proto.InternalMessageInfo

func (m *MsgSubmitSolution) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSubmitSolution) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *MsgSubmitSolution) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

func (m *MsgSubmitSolution) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

type MsgSubmitSolutionResponse struct {
}

func (m *MsgSubmitSolutionResponse) Reset()         { *m = MsgSubmitSolutionResponse{} }
func (m *MsgSubmitSolutionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitSolutionResponse) ProtoMessage()    {}
func (*MsgSubmitSolutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6250ca283f34de9, []int{11}
}
func (m *MsgSubmitSolutionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitSolutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitSolutionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitSolutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitSolutionResponse.Merge(m, src)
}
func (m *MsgSubmitSolutionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitSolutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitSolutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitSolutionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateVideoRenderingTask)(nil), "janction.videoRendering.v1.MsgCreateVideoRenderingTask")
	proto.RegisterType((*MsgCreateVideoRenderingTaskResponse)(nil), "janction.videoRendering.v1.MsgCreateVideoRenderingTaskResponse")
	proto.RegisterType((*MsgAddWorker)(nil), "janction.videoRendering.v1.MsgAddWorker")
	proto.RegisterType((*MsgAddWorkerResponse)(nil), "janction.videoRendering.v1.MsgAddWorkerResponse")
	proto.RegisterType((*MsgSubscribeWorkerToTask)(nil), "janction.videoRendering.v1.MsgSubscribeWorkerToTask")
	proto.RegisterType((*MsgSubscribeWorkerToTaskResponse)(nil), "janction.videoRendering.v1.MsgSubscribeWorkerToTaskResponse")
	proto.RegisterType((*MsgProposeSolution)(nil), "janction.videoRendering.v1.MsgProposeSolution")
	proto.RegisterType((*MsgProposeSolutionResponse)(nil), "janction.videoRendering.v1.MsgProposeSolutionResponse")
	proto.RegisterType((*MsgSubmitValidation)(nil), "janction.videoRendering.v1.MsgSubmitValidation")
	proto.RegisterType((*MsgSubmitValidationResponse)(nil), "janction.videoRendering.v1.MsgSubmitValidationResponse")
	proto.RegisterType((*MsgSubmitSolution)(nil), "janction.videoRendering.v1.MsgSubmitSolution")
	proto.RegisterType((*MsgSubmitSolutionResponse)(nil), "janction.videoRendering.v1.MsgSubmitSolutionResponse")
}

func init() {
	proto.RegisterFile("janction/videoRendering/v1/tx.proto", fileDescriptor_b6250ca283f34de9)
}

var fileDescriptor_b6250ca283f34de9 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xcf, 0x4f, 0xd4, 0x4e,
	0x14, 0x67, 0xbe, 0xbb, 0x2c, 0xcb, 0xfb, 0xa2, 0x62, 0x45, 0x28, 0x45, 0x9b, 0x4d, 0x49, 0xcc,
	0x86, 0xc4, 0x56, 0xfc, 0x45, 0x62, 0x08, 0x06, 0x4d, 0x4c, 0x38, 0x6c, 0x62, 0x0a, 0xc1, 0x84,
	0x0b, 0xe9, 0x76, 0xc6, 0x52, 0xd9, 0x76, 0x9a, 0x99, 0xee, 0x2a, 0x89, 0x07, 0xf5, 0x8a, 0x07,
	0x0f, 0xfe, 0x13, 0xde, 0xf8, 0x27, 0x4c, 0x3c, 0x72, 0xf4, 0x68, 0xe0, 0xc0, 0xbf, 0x61, 0xda,
	0x4e, 0x47, 0xb6, 0xb0, 0xbb, 0x2c, 0x09, 0xb7, 0xf9, 0xcc, 0x7b, 0xef, 0xf3, 0xf9, 0xbc, 0x97,
	0x79, 0x2d, 0xcc, 0xbf, 0x73, 0x42, 0x37, 0xf6, 0x69, 0x68, 0x75, 0x7c, 0x4c, 0xa8, 0x4d, 0x42,
	0x4c, 0x98, 0x1f, 0x7a, 0x56, 0x67, 0xd1, 0x8a, 0x3f, 0x98, 0x11, 0xa3, 0x31, 0x55, 0xb4, 0x3c,
	0xc9, 0xec, 0x4e, 0x32, 0x3b, 0x8b, 0xda, 0x8c, 0x4b, 0x79, 0x40, 0xb9, 0x15, 0xf0, 0xb4, 0x26,
	0xe0, 0x5e, 0x56, 0xa4, 0x4d, 0x79, 0xd4, 0xa3, 0xe9, 0xd1, 0x4a, 0x4e, 0xe2, 0xf6, 0x5e, 0x3f,
	0xbd, 0xbd, 0x88, 0x70, 0x91, 0x37, 0x9b, 0xd1, 0x6e, 0x67, 0x04, 0x19, 0xc8, 0x42, 0xc6, 0x4f,
	0x04, 0x73, 0x0d, 0xee, 0xbd, 0x64, 0xc4, 0x89, 0xc9, 0x66, 0x17, 0xcb, 0x86, 0xc3, 0x77, 0x15,
	0x15, 0xc6, 0xdc, 0x24, 0x46, 0x99, 0x8a, 0x6a, 0xa8, 0x3e, 0x6e, 0xe7, 0x50, 0x99, 0x84, 0x92,
	0xeb, 0x63, 0xf5, 0xbf, 0xf4, 0x36, 0x39, 0x2a, 0x3a, 0x00, 0x8f, 0x1d, 0x16, 0xbf, 0x62, 0x4e,
	0x40, 0xd4, 0x52, 0x0d, 0xd5, 0xaf, 0xd9, 0xa7, 0x6e, 0x14, 0x0d, 0xaa, 0x24, 0xc4, 0x59, 0xb4,
	0x9c, 0x46, 0x25, 0x4e, 0x74, 0xe2, 0x1d, 0x46, 0x1c, 0xcc, 0xd5, 0xd1, 0x34, 0x94, 0x43, 0x65,
	0x1a, 0x2a, 0x8c, 0xbc, 0x77, 0x18, 0x56, 0x2b, 0x35, 0x54, 0x2f, 0xdb, 0x02, 0x3d, 0x9b, 0xf8,
	0x72, 0x72, 0xb0, 0x90, 0xbb, 0x31, 0x56, 0x60, 0xbe, 0x4f, 0x1b, 0x36, 0xe1, 0x11, 0x0d, 0x39,
	0x51, 0x66, 0x60, 0x2c, 0x76, 0xf8, 0xee, 0xb6, 0x8f, 0x45, 0x3b, 0x95, 0x04, 0xae, 0x61, 0x63,
	0x1d, 0x26, 0x1a, 0xdc, 0x5b, 0xc5, 0xf8, 0x0d, 0x65, 0xbb, 0x84, 0xf5, 0xe9, 0x7b, 0x0e, 0xc6,
	0xa3, 0x76, 0xb3, 0xe5, 0xbb, 0xdb, 0x7e, 0x24, 0xba, 0xaf, 0x66, 0x17, 0x6b, 0x51, 0xc1, 0xd4,
	0x34, 0x4c, 0x9d, 0x26, 0xcd, 0x5d, 0x18, 0x5b, 0xa0, 0x36, 0xb8, 0xb7, 0xde, 0x6e, 0x72, 0x97,
	0xf9, 0x4d, 0x92, 0x45, 0x37, 0x68, 0x3e, 0x70, 0x07, 0x63, 0x46, 0x38, 0xcf, 0x85, 0x05, 0x4c,
	0x06, 0x91, 0x99, 0x15, 0xaa, 0x02, 0x09, 0x4d, 0x91, 0x65, 0xac, 0x40, 0xad, 0x17, 0xb7, 0x9c,
	0x82, 0x06, 0xd5, 0x6c, 0xba, 0x6b, 0xf9, 0x18, 0x24, 0x36, 0xbe, 0x22, 0x50, 0x1a, 0xdc, 0x7b,
	0xcd, 0x68, 0x44, 0x39, 0x59, 0xa7, 0xad, 0x76, 0xf2, 0xc0, 0xfa, 0xcc, 0xa3, 0x87, 0xad, 0x2e,
	0x91, 0x52, 0xb7, 0x48, 0x12, 0xe3, 0x82, 0x59, 0x2d, 0xd7, 0x4a, 0x49, 0x2c, 0xc7, 0x85, 0x11,
	0xde, 0x01, 0xed, 0xac, 0x1b, 0x39, 0xc8, 0x1f, 0x08, 0x6e, 0x65, 0xdd, 0x06, 0x7e, 0xbc, 0xe9,
	0xb4, 0x7c, 0xec, 0x5c, 0x81, 0xdb, 0x1a, 0xfc, 0xff, 0xd6, 0x6f, 0x11, 0xbe, 0x1a, 0xd0, 0x76,
	0x18, 0xa7, 0x4f, 0xb7, 0x6c, 0x9f, 0xbe, 0x52, 0xa6, 0x60, 0xb4, 0x93, 0xa8, 0xa7, 0x6f, 0xb7,
	0x6a, 0x67, 0xa0, 0xd0, 0xc9, 0xdd, 0x74, 0xd1, 0x8a, 0x56, 0x65, 0x2b, 0x9f, 0x11, 0xdc, 0x94,
	0xf1, 0x2b, 0x1a, 0xbb, 0x58, 0xd9, 0xb2, 0x5c, 0xd9, 0x82, 0xc5, 0x39, 0x98, 0x3d, 0x63, 0x21,
	0x37, 0xf8, 0x70, 0xbf, 0x02, 0xa5, 0x06, 0xf7, 0x94, 0xef, 0x08, 0xd4, 0x9e, 0x9f, 0x8b, 0x25,
	0xb3, 0xf7, 0xd7, 0xcd, 0xec, 0xb3, 0xa0, 0xda, 0xf3, 0x4b, 0x16, 0xca, 0x37, 0xed, 0xc1, 0xf8,
	0xbf, 0xed, 0xad, 0x0f, 0x60, 0x93, 0x99, 0xda, 0x83, 0x8b, 0x66, 0x4a, 0xa1, 0x7d, 0x04, 0xb7,
	0xcf, 0x5f, 0xdd, 0xc7, 0x03, 0xb8, 0xce, 0xad, 0xd2, 0x96, 0x2f, 0x53, 0x25, 0xdd, 0xec, 0xc1,
	0x8d, 0xe2, 0xaa, 0x9a, 0x03, 0x08, 0x0b, 0xf9, 0xda, 0xd3, 0xe1, 0xf2, 0xa5, 0xf4, 0x47, 0x98,
	0x3c, 0xb3, 0x78, 0xd6, 0xe0, 0x66, 0xba, 0x0a, 0xb4, 0xa5, 0x21, 0x0b, 0xa4, 0x7a, 0x07, 0xae,
	0x17, 0x76, 0xe5, 0xfe, 0x85, 0xa8, 0x64, 0xdb, 0x4f, 0x86, 0x4a, 0xcf, 0x75, 0xb5, 0xd1, 0x4f,
	0x27, 0x07, 0x0b, 0xe8, 0xc5, 0xf2, 0xaf, 0x23, 0x1d, 0x1d, 0x1e, 0xe9, 0xe8, 0xcf, 0x91, 0x8e,
	0xbe, 0x1d, 0xeb, 0x23, 0x87, 0xc7, 0xfa, 0xc8, 0xef, 0x63, 0x7d, 0x64, 0xcb, 0xf0, 0xfc, 0x78,
	0xa7, 0xdd, 0x34, 0x5d, 0x1a, 0x58, 0x3d, 0xfe, 0xcf, 0xcd, 0x4a, 0xfa, 0xf3, 0x7d, 0xf4, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x2c, 0x35, 0xef, 0xb0, 0x31, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateGame create a game.
	CreateVideoRenderingTask(ctx context.Context, in *MsgCreateVideoRenderingTask, opts ...grpc.CallOption) (*MsgCreateVideoRenderingTaskResponse, error)
	// Adds a new worker
	AddWorker(ctx context.Context, in *MsgAddWorker, opts ...grpc.CallOption) (*MsgAddWorkerResponse, error)
	SubscribeWorkerToTask(ctx context.Context, in *MsgSubscribeWorkerToTask, opts ...grpc.CallOption) (*MsgSubscribeWorkerToTaskResponse, error)
	// Propose a solution for the test of the nodes to validate
	ProposeSolution(ctx context.Context, in *MsgProposeSolution, opts ...grpc.CallOption) (*MsgProposeSolutionResponse, error)
	// Propose a solution for the test of the nodes to validate
	SubmitValidation(ctx context.Context, in *MsgSubmitValidation, opts ...grpc.CallOption) (*MsgSubmitValidationResponse, error)
	// Submits the solution to IPFS
	SubmitSolution(ctx context.Context, in *MsgSubmitSolution, opts ...grpc.CallOption) (*MsgSubmitSolutionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateVideoRenderingTask(ctx context.Context, in *MsgCreateVideoRenderingTask, opts ...grpc.CallOption) (*MsgCreateVideoRenderingTaskResponse, error) {
	out := new(MsgCreateVideoRenderingTaskResponse)
	err := c.cc.Invoke(ctx, "/janction.videoRendering.v1.Msg/CreateVideoRenderingTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddWorker(ctx context.Context, in *MsgAddWorker, opts ...grpc.CallOption) (*MsgAddWorkerResponse, error) {
	out := new(MsgAddWorkerResponse)
	err := c.cc.Invoke(ctx, "/janction.videoRendering.v1.Msg/AddWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubscribeWorkerToTask(ctx context.Context, in *MsgSubscribeWorkerToTask, opts ...grpc.CallOption) (*MsgSubscribeWorkerToTaskResponse, error) {
	out := new(MsgSubscribeWorkerToTaskResponse)
	err := c.cc.Invoke(ctx, "/janction.videoRendering.v1.Msg/SubscribeWorkerToTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ProposeSolution(ctx context.Context, in *MsgProposeSolution, opts ...grpc.CallOption) (*MsgProposeSolutionResponse, error) {
	out := new(MsgProposeSolutionResponse)
	err := c.cc.Invoke(ctx, "/janction.videoRendering.v1.Msg/ProposeSolution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitValidation(ctx context.Context, in *MsgSubmitValidation, opts ...grpc.CallOption) (*MsgSubmitValidationResponse, error) {
	out := new(MsgSubmitValidationResponse)
	err := c.cc.Invoke(ctx, "/janction.videoRendering.v1.Msg/SubmitValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitSolution(ctx context.Context, in *MsgSubmitSolution, opts ...grpc.CallOption) (*MsgSubmitSolutionResponse, error) {
	out := new(MsgSubmitSolutionResponse)
	err := c.cc.Invoke(ctx, "/janction.videoRendering.v1.Msg/SubmitSolution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateGame create a game.
	CreateVideoRenderingTask(context.Context, *MsgCreateVideoRenderingTask) (*MsgCreateVideoRenderingTaskResponse, error)
	// Adds a new worker
	AddWorker(context.Context, *MsgAddWorker) (*MsgAddWorkerResponse, error)
	SubscribeWorkerToTask(context.Context, *MsgSubscribeWorkerToTask) (*MsgSubscribeWorkerToTaskResponse, error)
	// Propose a solution for the test of the nodes to validate
	ProposeSolution(context.Context, *MsgProposeSolution) (*MsgProposeSolutionResponse, error)
	// Propose a solution for the test of the nodes to validate
	SubmitValidation(context.Context, *MsgSubmitValidation) (*MsgSubmitValidationResponse, error)
	// Submits the solution to IPFS
	SubmitSolution(context.Context, *MsgSubmitSolution) (*MsgSubmitSolutionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateVideoRenderingTask(ctx context.Context, req *MsgCreateVideoRenderingTask) (*MsgCreateVideoRenderingTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVideoRenderingTask not implemented")
}
func (*UnimplementedMsgServer) AddWorker(ctx context.Context, req *MsgAddWorker) (*MsgAddWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddWorker not implemented")
}
func (*UnimplementedMsgServer) SubscribeWorkerToTask(ctx context.Context, req *MsgSubscribeWorkerToTask) (*MsgSubscribeWorkerToTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscribeWorkerToTask not implemented")
}
func (*UnimplementedMsgServer) ProposeSolution(ctx context.Context, req *MsgProposeSolution) (*MsgProposeSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProposeSolution not implemented")
}
func (*UnimplementedMsgServer) SubmitValidation(ctx context.Context, req *MsgSubmitValidation) (*MsgSubmitValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitValidation not implemented")
}
func (*UnimplementedMsgServer) SubmitSolution(ctx context.Context, req *MsgSubmitSolution) (*MsgSubmitSolutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitSolution not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateVideoRenderingTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateVideoRenderingTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateVideoRenderingTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoRendering.v1.Msg/CreateVideoRenderingTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateVideoRenderingTask(ctx, req.(*MsgCreateVideoRenderingTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddWorker)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoRendering.v1.Msg/AddWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddWorker(ctx, req.(*MsgAddWorker))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubscribeWorkerToTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubscribeWorkerToTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubscribeWorkerToTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoRendering.v1.Msg/SubscribeWorkerToTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubscribeWorkerToTask(ctx, req.(*MsgSubscribeWorkerToTask))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ProposeSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgProposeSolution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ProposeSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoRendering.v1.Msg/ProposeSolution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ProposeSolution(ctx, req.(*MsgProposeSolution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitValidation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoRendering.v1.Msg/SubmitValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitValidation(ctx, req.(*MsgSubmitValidation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitSolution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitSolution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitSolution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.videoRendering.v1.Msg/SubmitSolution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitSolution(ctx, req.(*MsgSubmitSolution))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "janction.videoRendering.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVideoRenderingTask",
			Handler:    _Msg_CreateVideoRenderingTask_Handler,
		},
		{
			MethodName: "AddWorker",
			Handler:    _Msg_AddWorker_Handler,
		},
		{
			MethodName: "SubscribeWorkerToTask",
			Handler:    _Msg_SubscribeWorkerToTask_Handler,
		},
		{
			MethodName: "ProposeSolution",
			Handler:    _Msg_ProposeSolution_Handler,
		},
		{
			MethodName: "SubmitValidation",
			Handler:    _Msg_SubmitValidation_Handler,
		},
		{
			MethodName: "SubmitSolution",
			Handler:    _Msg_SubmitSolution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "janction/videoRendering/v1/tx.proto",
}

func (m *MsgCreateVideoRenderingTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateVideoRenderingTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateVideoRenderingTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reward != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Reward))
		i--
		dAtA[i] = 0x30
	}
	if m.Threads != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Threads))
		i--
		dAtA[i] = 0x28
	}
	if m.EndFrame != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndFrame))
		i--
		dAtA[i] = 0x20
	}
	if m.StartFrame != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.StartFrame))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateVideoRenderingTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateVideoRenderingTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateVideoRenderingTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddWorker) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddWorker) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddWorker) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PublicIp) > 0 {
		i -= len(m.PublicIp)
		copy(dAtA[i:], m.PublicIp)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicIp)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddWorkerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddWorkerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddWorkerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubscribeWorkerToTask) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubscribeWorkerToTask) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubscribeWorkerToTask) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubscribeWorkerToTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubscribeWorkerToTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubscribeWorkerToTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProposeSolution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProposeSolution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProposeSolution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Solution) > 0 {
		for iNdEx := len(m.Solution) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Solution[iNdEx])
			copy(dAtA[i:], m.Solution[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Solution[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgProposeSolutionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgProposeSolutionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgProposeSolutionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitValidation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitValidation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitValidation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Valid {
		i--
		if m.Valid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if m.FilesAmount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FilesAmount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitValidationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitValidationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitValidationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitSolution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitSolution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitSolution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Cid) > 0 {
		i -= len(m.Cid)
		copy(dAtA[i:], m.Cid)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Cid)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TaskId) > 0 {
		i -= len(m.TaskId)
		copy(dAtA[i:], m.TaskId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TaskId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitSolutionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitSolutionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitSolutionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateVideoRenderingTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.StartFrame != 0 {
		n += 1 + sovTx(uint64(m.StartFrame))
	}
	if m.EndFrame != 0 {
		n += 1 + sovTx(uint64(m.EndFrame))
	}
	if m.Threads != 0 {
		n += 1 + sovTx(uint64(m.Threads))
	}
	if m.Reward != 0 {
		n += 1 + sovTx(uint64(m.Reward))
	}
	return n
}

func (m *MsgCreateVideoRenderingTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddWorker) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicIp)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddWorkerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubscribeWorkerToTask) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubscribeWorkerToTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgProposeSolution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Solution) > 0 {
		for _, s := range m.Solution {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgProposeSolutionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitValidation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.FilesAmount != 0 {
		n += 1 + sovTx(uint64(m.FilesAmount))
	}
	if m.Valid {
		n += 2
	}
	return n
}

func (m *MsgSubmitValidationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitSolution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TaskId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Cid)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitSolutionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateVideoRenderingTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateVideoRenderingTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateVideoRenderingTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartFrame", wireType)
			}
			m.StartFrame = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartFrame |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndFrame", wireType)
			}
			m.EndFrame = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndFrame |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threads", wireType)
			}
			m.Threads = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threads |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reward", wireType)
			}
			m.Reward = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reward |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateVideoRenderingTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateVideoRenderingTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateVideoRenderingTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddWorker) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddWorker: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddWorker: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicIp", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicIp = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddWorkerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddWorkerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddWorkerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubscribeWorkerToTask) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubscribeWorkerToTask: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubscribeWorkerToTask: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubscribeWorkerToTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubscribeWorkerToTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubscribeWorkerToTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProposeSolution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProposeSolution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProposeSolution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Solution", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Solution = append(m.Solution, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgProposeSolutionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgProposeSolutionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgProposeSolutionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitValidation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitValidation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitValidation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilesAmount", wireType)
			}
			m.FilesAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FilesAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Valid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Valid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitValidationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitValidationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitValidationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitSolution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitSolution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitSolution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TaskId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TaskId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitSolutionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitSolutionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitSolutionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
